env:
  global:
  - CXX=g++-4.8
  - secure: J3bd4Arv6RofyD2lH5pc56BpAsYGliac6AQvadet43DSQ4LQWWV15MUCrak+g9ojptKePX07dfYVfNLU0nRlqEMCeh//ayIAKffGWeOlNfA7/ajUfU3i1Y7P5breYin3tS1hXyREAyKrLksexs8/0DTBz+848v9vbbqNA6AIlJwvgKTT8QcisROixhREoI+yTyNvUqFBBu40TOOyKf3CoXLjgagY/hZCGXvwria9toPGQC7YbpSvnBcWVpRwn50FDPOh70hdEaC96Y/c0sziOLuxrX7MKj0hy1UTD+UdM9J1oFot4LRgSl37t4EE+u7nD1MCGGwKUVVeg0sK6orpPez24fuoA8lnaLlKc3fsLM4boIXLVMchvEmtJ8fNX/3qYid9u1x8IAlT9GShxjuSusY79l4UzZb1Rm9Ge6VWTkxbrQsdbAlzUrExiAKiYPGrqFYr4bUZzkfMbe6szfavvUKgHceNVsOJ+GRxCZklBDDovwElRaw2cHumCCNKVCAOeUerk4DUjssFyBFh5luN8wpWd/XeGJE3sD00Iwp/ytk2xBnYUXVdW2X205xJa65u719iEum6wfnDk1jEAB0BsyOnrIhd2fcf8nbNj9KBDLcdCGZS4bqcsrrUge+06it+izt8+an2JNLCXhJ4SMngKAmaf+JcmJwBql2oaGHGhVA=
  - secure: UfAq7anm1LiffXtgm4Apt+POJfoO/lWjNpvlBQPSSrxHmBVMiM5+g2OsA/zrY/1tMNeb3USUjAJmSkzGwUjanX0XsJyx3RjQd81bBdi+6hEWCmhfSyiwilnul5AZ2K2si7fA2pfRJq/rYzc7M+vETflcy/gl5bSTPj9ltFs747Q63b6pfWKpvNdUIyEsqqfjIGrmjHalzFi2C7AVM6Z6kBwSjHqlsl5vLl3L/BDywxcI+gra0wV1VqMeL9nUSnK3rEwGCZ5ggGVasOOVrJ/wAZiYvpOuRvvdvBdeIwPlPNvLN4w9vh25KsllwAOn6pdkJxDyoKsRB7GV9PFvaoVs5ZpQYwkqf1MN37bH2ef8F6MgXeVMtI5+LqCEgoYDaJfPKamK62d8/jkHmq+U3XzqUy+EnPWFU0STZnjTFR7BqBtIapl6Jaw2dqI3sT6Es2GhHPVdQnGFKZqf6/XvJk0tjixNYPWoKjWsdkMwBaguBAqmM3NTr7BJCkeHyeaWfwZVOYoLWLuQm6GQWmMVbglRcDvD1R+49OtdnxL83v6AoSJCwAlQ6mJ1zQuLCrw7f+ngva7SEsdHe2r3Rb6+p/RscxFKssOiHwqHa90u6lFlnTOtmRSD8I0P4FC0CY1U001HhbxWCKqD2+4T63fpP34nAIxotNFXfefUs78yqHvPurw=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  sauce_connect: true
language: node_js
node_js:
- 4
- 6
- 7
script:
- yarn lint
- yarn bower
- yarn nahual
notifications:
  email: false
