env:
  global:
  - secure: N0KncmEji+Aqkvq0TU/8CwT8zrhgoVZZYeUVuNzet4n0VGfmBhOMMK/gSfNZ/+Mc9TF+1mJW48EnLAsb8Y4UsxPYS5Jrmxu2EoAFuWugPJTZ64rV3nGbWpFhmOoYxSR9TnzeMRkfNsIz/TwAoG2hlpZlqhSvB1XYZB5J+2CZO8LZJK2riEM2vmHnUU+AQULA/jnv4JyNQxRy+hkT9HDtSJzftGl2bQ2sW89ac3Jw3iQlN0RxUtoPWWC3lVcV5waPNYv4fMlbGHPtm/Q1ptp3ugoapx/I+NASJ797e9jLr1jTou28yePRKpf6E3XXx1Bs9F0pqwzYp+atAuMs5o7ilDGztFK/2cRJwtuTWRw1TTKG1OdzRmlE46wGgrNLUrQPpV2LNhvc5Jj70mFpFfG7KSDHdX+Hi/BM8iwBLhuKw0yCnUjHRgAzPX481P7shHh2FEhUcw3SiL7Kd5WoITukw9KUaWvmaGoqHExN3MM54DXnerj3iqdUg2ynUg9xuffYTN1ETSqxV5bqF0z9rdzXUehCbo/zI1mlJ4IZGzJa5oIT7p6i/l0pvCAtQsZyPJWHB6fpT8WuquhY8VHECsl5bqVToQwiUR43J2QYOpG3SRbwiKcYeFTXc6XOZlmaoP90RdaDQ2jDCkNXjFyFWP4f4Lwe+/kp8Y47CDJ3nkqCHzc=
  - secure: BVAk9JPuXEKh2F1Zm8rQSuSnuP1krDbNWZ0sICRAQ1NmthwTdBj5jweW0fQQckoxAEZKwADWPyjR0ALKd2CrM9mmjcaStg8TWVS9744nUlCIQWEm96z8ZC4NmFxjC12AoHsr+xqglzkmZUo0jsM7rBwwm52jdgknZLAkLY79Hos1deHReoAjiraYkXfYfbM4CKKUyaRrGayvdcsAaz0mVE4T0qSo+fTDeKkBHYYSrBKYNl+eH0qrbyOH7RteaJUNbqieZvM46OlLCupMyP16DmZxlO9jiEIEjSkdBGymxMrFqfx99EkqrM8Bo2+Y20bVmCpsUDiTO5bi4EBt5MaBbG3LcW9gRFrYx4Pe9Jxz9I9cZgIJIKGrS7PQHcw/dqmGMAzquNhuP0CpBGSQ4Bl9yhnxSwq5Y3WHxulUlXyzN5LhnTuZWilOkisSajVfHEP41VAK6JzJSug3w532rbNLixNo+haCqoXg6C9LZkNrYgOmhG9pv3lXN5w9sGVHjbHjCSoERrA2VxR/JQsA473fDCn+BupFJJ+DjG7g5XQUKekUz/JiavwbJC+8xyOBvjm6TqGEFUji2tzWX4RRm5drdEBpjPVlhBC1+l1p0Jj8vc72Or/p2e/hkslYC5vNKicTycowQ5qgcGnIaXOwb5HbGdFhkDzAXNEB4HQEw3mRsKE=
addons:
  sauce_connect: true
language: node_js
node_js:
- 0.1
script:
- 'npm run lint'
- 'npm run bower'
- 'npm run nahual'
