addons:
  sauce_connect: true
language: node_js
node_js:
- 0.1
- 0.11
- 0.12
- 4
- 5
- 6
- iojs
script:
- npm run lint
- npm run bower
- npm run nahual
env:
  global:
  - secure: bdxsJSpAzpMcCzZFrRr9927ysMi8MRl0J9ndJnYZMFLD46Dt/K7gUIkh4YMvY5Qd4WAC9pZ9KTHLm4E/UR0CQ3Fe0IGDLmhI8LD8PTIvVWVyZe0djMVXR+O4RawKsitUOMoF9v2iLV8F9+Bbtbm0izcj0rAzH/EPsYXEDlz9F3E9iu7xIdpzGyEvBuj+GGIag66x6Rpd7BhohohcUo5x9dB8kOqZuhJbsohZc+ZI0Z6I1D0SmBeadnkMl6oqWwayspP4XPukllTWA1g/TweEevrfb9rxZ2CTDXZ9qEKsCpYrSrZyZc6eIM5q2m1t6UY933MFPWCu6WMG3TLulq3eTn/Rd42wHh7igfZfZlF+TBF7UQ22NV9Ma3g5HycBKFV0IMuMuHaN8T3oT84PJPNdIOhohL2WFAYgZYbAICOmkze4FOSqJ5AfqNBgbokCWbOdupsj+tcbdbn8avUvLXVJszYgg+Ty+OTS3Mv+qec789xptCnUQjCYGskha4pLV8pTz1V75bHcjNzjTYrl43We5DGoXK5toVGPak9I+xrYMkZgbCoPZQrP3Phfn2P04p0k2/KYgHMTn1mPhGAVAKcNzTjH1oo+Nkywwy+lf8j+98aE7/k6S+N/x+rftpaBqwMEWnNaXxMViQqgGUGICXA3FTSSGRGfpQelzK/d+88lJDM=
  - secure: LqCdB3I8iFP4CzUMlx5H9iiNJitDn8nZjLd6HPmNOVPNFE8QmfJxR8hSoH/KG1TWaSxElAR0QZ29TtmzJbrsEbJz3fnFNT99YFDMSxwVyrzd4YdQ5hnbUlco2zmn/0amXTKX+TJ9LBVHXx+2kLdRp1I5p+fKez8jgOdjlZ8ewr6hdBdQbavGb1VLN6Wo8rfGXlGavBYnF9ZyhblCggZKDchhOE9L8l+VAf6cC+/EO9Pbe2xPDOmevatjUcvhG7WslRs7F/kftyNaDhTOYNqr2p1Hn58dscbzzwu8sUXxiu000DN5OLaMYjys8ivjjx2nYfoxrCnPnQGwt6aBAASRVZB848+dWHhYjaAMTVibC01EwJRLK6GKRX8pGf+7JfqjT+90kHoQIECQTEagCPe6ZojZZQmON+dRUTW59fntwqA2FDBc93S0DlCIYWppAZrJ6LtoFMxd9YGCktt6Y5n6HtuKybhJPtle3kHx17lv5S6C7zgcl2nQZLkAvzhwOCX3Y986OkfUOdfU8jbluQyOOObEsP8/Gap94VqgbM9s9bd3fpHD42bHiItY+XJT/3Uqipl6KbOtZ7cYNHRvcrkkJf7sVBDRkB2M1F1d7NknCZ9HUFzyXC0KJL1z62srAMOB1LVaBqdoDsm99wQ3QZCX4tZ4jCoP5yDwvEWgX/vg1W4=
